name: 'Tests (Ubuntu)'

on:
  push:
  pull_request:
  schedule:
    - cron:  '45 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: xdebug.mode=develop
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Lint PHP
        run: |
          find . -name \*.php ! -path './vendor/*' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: |
          vendor/bin/simple-phpunit --colors
